# Generated by Django 5.0.6 on 2024-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloguser_profile_image_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
